apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: saga
type: Opaque
stringData:
  order-username: order_user
  order-password: order_pass
  payment-username: payment_user
  payment-password: payment_pass
  inventory-username: inventory_user
  inventory-password: inventory_pass
